name: example
description: Exemplo de como utilizar o package brasil_datetime
version: 1.0.0
homepage: https://github.com/flutterbootcamp/brasil_datetime
publish_to: 'none'

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  brasil_datetime: 
    path: ../

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
