name: example
description: Exemplo de como utilizar o package brasil_datetime
version: 1.0.0
homepage: https://github.com/flutterbootcamp/brasil_datetime
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  brasil_datetime: 
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.25.14
