name: brasil_datetime
description: Extensões para a classe DateTime para facilitar a formatação em pt_BR
version: 0.3.0
homepage: https://github.com/flutterbootcamp/brasil_datetime
repository: https://github.com/flutterbootcamp/brasil_datetime
issue_tracker: https://github.com/flutterbootcamp/brasil_datetime/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  intl: ^0.18.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.2