name: brasil_datetime
description: Extensões para objetos DateTime em pt_BR
version: 0.1.2
homepage: https://github.com/flutterbootcamp/brasil_datetime

environment:
  sdk: '>=2.18.3 <3.0.0'

dependencies:
  intl: ^0.17.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0